no change     /media02/ltnghia07/miniconda3/condabin/conda
no change     /media02/ltnghia07/miniconda3/bin/conda
no change     /media02/ltnghia07/miniconda3/bin/conda-env
no change     /media02/ltnghia07/miniconda3/bin/activate
no change     /media02/ltnghia07/miniconda3/bin/deactivate
no change     /media02/ltnghia07/miniconda3/etc/profile.d/conda.sh
no change     /media02/ltnghia07/miniconda3/etc/fish/conf.d/conda.fish
no change     /media02/ltnghia07/miniconda3/shell/condabin/Conda.psm1
no change     /media02/ltnghia07/miniconda3/shell/condabin/conda-hook.ps1
no change     /media02/ltnghia07/miniconda3/lib/python3.13/site-packages/xontrib/conda.xsh
no change     /media02/ltnghia07/miniconda3/etc/profile.d/conda.csh
no change     /media02/ltnghia07/.bashrc
No action taken.

CondaError: Run 'conda init' before 'conda activate'

/media02/ltnghia07/StyleMe/sketch_generation/evaluate.py:56: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if args.checkpoint is not 'None':
/media02/ltnghia07/miniconda3/envs/deep/lib/python3.10/site-packages/torch/nn/modules/instancenorm.py:115: UserWarning: input's size at dim=1 does not match num_features. You can silence this warning by not passing in num_features, which is not used because affine=False
  warnings.warn(
Namespace(path_content='/media02/ltnghia07/evaluate-2d/dataset/sample', path_result='/media02/ltnghia07/evaluate-2d/sample', im_size=256, gpu_id=0, norm_layer='instance', checkpoint='/media02/ltnghia07/StyleMe/sketch_generation/model/train_results/finetune3/models/29999_model.pth')
saved model loaded
begin generating images ...
generating the 0th image
generating the 1th image
generating the 2th image
generating the 3th image
generating the 4th image
